/** Export icons and documentation pictures from the production character.
 * Start npm run dev, then run: npm run art-assets [http://localhost:5173]
 */
import { readFile, writeFile } from 'node:fs/promises';
import { chromium } from '@playwright/test';

const base = process.argv[2] ?? 'http://localhost:5173';
const root = new URL('../', import.meta.url);
const browser = await chromium.launch();
try {
  const page = await browser.newPage({ viewport: { width: 1200, height: 1090 }, deviceScaleFactor: 1, locale: 'zh-CN' });
  await page.goto(`${base}/tools/gallery.html`);
  await page.locator('canvas[data-ready="true"]').waitFor();
  await page.screenshot({ path: new URL('docs/character.png', root).pathname });
  const icon = await page.evaluate(async () => {
    const moduleUrl = '/src/render/cat.ts';
    const { loadCatArt, drawCat, DEFAULT_POSE } = await import(moduleUrl);
    await loadCatArt();
    // Export the actual composed sprite as flat SVG pixel runs, so icons
    // cannot silently acquire smooth rotated ears or a different silhouette.
    const canvas = document.createElement('canvas');
    canvas.width = canvas.height = 48;
    const ctx = canvas.getContext('2d');
    ctx.scale(0.5, 0.5);
    drawCat(ctx, 48, 54, { ...DEFAULT_POSE, legs: -0.5, tilt: -0.12 });
    const pixels = ctx.getImageData(0, 0, 48, 48).data;
    const colorAt = (x, y) => {
      const i = (y * 48 + x) * 4;
      return pixels[i + 3] === 0 ? '' : `#${Array.from(pixels.slice(i, i + 3), (v) => v.toString(16).padStart(2, '0')).join('')}`;
    };
    const runs = [];
    for (let y = 0; y < 48; y++) for (let x = 0; x < 48;) {
      const color = colorAt(x, y);
      const start = x++;
      while (x < 48 && colorAt(x, y) === color) x++;
      if (color) runs.push(`<path fill="${color}" d="M${start} ${y}h${x - start}v1H${start}Z"/>`);
    }
    return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 48 48" shape-rendering="crispEdges">
<!-- Generated by tools/art-assets.mjs from the production pixel character. -->
<path fill="#2b2350" d="M6 0H42V2H46V6H48V42H46V46H42V48H6V46H2V42H0V6H2V2H6Z"/>
${runs.join('\n')}
</svg>\n`;
  });
  await writeFile(new URL('public/icon.svg', root), icon);
  for (const size of [180, 512]) {
    const png = await page.evaluate(async ({ icon, size }) => {
      const image = new Image();
      image.src = `data:image/svg+xml;charset=utf-8,${encodeURIComponent(icon)}`;
      await image.decode();
      const canvas = document.createElement('canvas');
      canvas.width = canvas.height = size;
      const ctx = canvas.getContext('2d');
      ctx.imageSmoothingEnabled = false;
      ctx.drawImage(image, 0, 0, size, size);
      return canvas.toDataURL('image/png').split(',')[1];
    }, { icon, size });
    await writeFile(new URL(`public/icon-${size}.png`, root), Buffer.from(png, 'base64'));
  }

  // The same checked-in recording used by the cross-engine replay test.
  const social = await readFile(new URL('e2e/social.spec.ts', root), 'utf8');
  const challenge = social.match(/const GOLDEN = '([^']+)'/)[1];
  const phone = await browser.newPage({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 1, isMobile: true, hasTouch: true, locale: 'zh-CN' });
  await phone.addInitScript(() => localStorage.setItem('catflap.name', '小橘'));
  await phone.goto(`${base}/?c=${challenge}`);
  await phone.locator('#app[data-phase="ready"]').waitFor();
  await phone.evaluate(() => document.fonts.ready);
  await phone.waitForTimeout(600); // allow the initial CSS screen transitions to finish
  const ready = await phone.screenshot();
  await phone.goto(`${base}/?c=${challenge}&bot=15`);
  await phone.waitForFunction(() => document.querySelector('.score')?.textContent === '9', null, { timeout: 30_000 });
  await phone.waitForTimeout(300); // let +1 rise clear of the face
  const flying = await phone.screenshot();
  await phone.locator('#app[data-phase="gameover"]').waitFor({ timeout: 30_000 });
  await phone.locator('#app.can-retry').waitFor();
  // The retry lockout ends before the score count-up. Capture the settled
  // value so the result card and the ranking don't show different scores.
  await phone.waitForFunction(() => document.querySelector('.final-score')?.textContent === '15');
  await phone.waitForFunction(() => Number(getComputedStyle(document.querySelector('.retry-hint')).opacity) > 0.95);
  const over = await phone.screenshot();
  const panels = [ready, flying, over].map((p) => p.toString('base64'));
  const composite = await page.evaluate(async (panels) => {
    const canvas = document.createElement('canvas');
    canvas.width = 1234; canvas.height = 876;
    const ctx = canvas.getContext('2d');
    ctx.fillStyle = '#2b2350'; ctx.fillRect(0, 0, canvas.width, canvas.height);
    for (const [i, panel] of panels.entries()) {
      const image = new Image(); image.src = `data:image/png;base64,${panel}`;
      await image.decode();
      ctx.drawImage(image, 16 + i * 406, 16);
    }
    return canvas.toDataURL('image/png').split(',')[1];
  }, panels);
  await writeFile(new URL('docs/preview.png', root), Buffer.from(composite, 'base64'));
  console.log('Exported public/icon.svg, icon-180.png, icon-512.png, docs/character.png and docs/preview.png');
} finally {
  await browser.close();
}
